import Head from "next/head";

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello World!</h1>
        <h2>Next Default Setup</h2>
        <nav>
          <ul>
            <li></li>
          </ul>
        </nav>
      </main>
    </div>
  );
};

export default Home;
